Import('variant')

import os

artefacts = {}

artefacts['incs'] = [os.path.join("include", "rttest.h"),
                     os.path.join("include", "rttest_format.h"),
                     os.path.join("include", "rttest_priv.h")]
srcs = [os.path.join("src", "rttest.c")]
artefacts['rttestobjs'] = [variant['envnp'].StaticObject(src) for src in srcs]

# For some reason, scons decides to remove the CPPPATH I add if I
# don't use a leading "#"...
rttenv = variant['envnp'].Clone()
rttenv.Append(CPPPATH = [os.path.join("#rttest", "test"),
                         os.path.join("#rttest", "include")])

testrtt_srcs = [os.path.join("test", "unittest1.c"),
                os.path.join("test", "unittest2.c")]
artefacts['testrttobjs'] = [rttenv.StaticObject(src) for src in testrtt_srcs]
artefacts['testrttobjs'].append(rttenv.StaticObject(os.path.join("test", "testme.c")))
artefacts['testrttobjs'].append(rttenv.StaticObject(os.path.join("test", "testrttest.c")))

variant['env'].Install(variant['install_bin'],
        os.path.join("#rttest", "scripts", "rttest2text.py"))

Return('artefacts')
