Import('variant')

import os

artefacts = {}

artefacts['incs'] = [os.path.join("include", "rthsm.h")]
srcs = [os.path.join("src", "rthsm.c")]
artefacts['objs'] = [variant['env'].StaticObject(src) for src in srcs]
artefacts['testsrcs'] = [os.path.join("test", "unittest.c")]

Return('artefacts')
